spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
      # show_sql: true
      format_sql: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
