spring:
  elastic:
    url : ${ELASTIC_SEARCH_URL}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
      # show_sql: true
      format_sql: true
  elasticsearch:
    password: ${ELASTIC_PASSWORD}
    username: ${ELASTIC_USERNAME}
